apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: grafana-agent
data:
  agent.yaml: |
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          k8s_cluster: farmrpg-etl
      configs:
      - name: default
        remote_write:
        - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
          basic_auth:
            username: 467418
            password: ${GRAFANA_API_KEY}
        scrape_configs:
        - job_name: cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - replacement: kubernetes.default.svc:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
            source_labels:
            - __meta_kubernetes_node_name
            target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
    integrations:
      node_exporter:
        rootfs_path: /host/root
        sysfs_path: /host/sys
        procfs_path: /host/proc
        set_collectors:
        - boottime
        - cpu
        - filesystem
        - loadavg
        - meminfo
        - vmstat
