apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
  namespace: etl
spec:
  selector:
    matchLabels:
      app: etl
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: etl
    spec:
      initContainers:
      - name: migrations
        image: ghcr.io/coderanger/farmrpg-etl2:main
        imagePullPolicy: Always
        command:
        - .venv/bin/python
        - manage.py
        - migrate
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp/service-account.json
        envFrom:
        - secretRef:
            name: credentials
        resources:
          requests:
            memory: 1G
          limits:
            memory: 2G
        volumeMounts:
        - mountPath: /gcp
          name: gcp
      containers:
      - name: etl
        image: ghcr.io/coderanger/farmrpg-etl2:main
        imagePullPolicy: Always
        command:
        - .venv/bin/python
        - -m
        - uvicorn
        - --host=0.0.0.0
        - --port=443
        - --access-log
        - --no-server-header
        - --ssl-keyfile=/tls/tls.key
        - --ssl-certfile=/tls/tls.crt
        - etl.asgi:application
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp/service-account.json
        envFrom:
        - secretRef:
            name: credentials
        resources:
          requests:
            memory: 1G
          limits:
            memory: 2G
        securityContext:
          capabilities:
            add: [NET_BIND_SERVICE]
            drop: [ALL]
          runAsUser: 65534
          runAsGroup: 65534
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /gcp
          name: gcp
        - mountPath: /tls
          name: tls
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: gcp
        secret:
          secretName: gcp
      - name: tls
        secret:
          secretName: tls
