apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: etl
type: Opaque
stringData:
    AUTH_COOKIE: ENC[AES256_GCM,data:5hoAxQXVoTT8pO2ofaqiwM1LLAkTqSIxwBn7KSjmXSufUTQwbmx5ZXIAyyvQbR709v6bSvNm7/f24sXMi4hhVbZuOlifpepZfBNQqWuwAmgvzPp8CsBNavE1T5PLN/QDfH9Eie+3YgXHP8QNnIKr809cdlcYldDeN2u+7t320N/TPfBpzuF+bW60TOrBxGy2MIf1z53HyUSEmILHOmVEi6Q=,iv:w1kGod3owa1WcaK1e8r5sAfV8l0ym+HHM1P12dOorqM=,tag:ep6G/A4bUa0Z1FzDxiTaWg==,type:str]
    BOT_AUTH_COOKIE: ENC[AES256_GCM,data:EPT3tHeG1Hb80G512vF39myk7/qdKl+pAuw8DD6wDemc4+qGEsH7op6NXwcpI6mQsCZrN0SStTlJlQWo9b+ZoG7JuX7J258WV3id8hFBrbQf0wyteqDk1+ibx8tlbl1N4NGCQynDbL4kZdZU0bqdINBUcgu2IQZr+XhPcxDMT/vUgtlmbICxUGoffkuAtm7DNxSq/aZlhU5Pij3VSw==,iv:AZRRrvB0BPWVwpbBzPyKTxxCQJ8rodVZxJqUyLQm5MY=,tag:XpVy+pWGKTJ21poZQPe64A==,type:str]
    ALPHA_AUTH_COOKIE: ENC[AES256_GCM,data:mjC+qwAQpo2g0DkJGA2S4UHVe1J2JB3xICL9PINFZ7fnGKUJHcrRnYlucrPWDzJ219/qckC0Mn9LuiGLfABTHrd4FOy0W+NIHwyOwOhX6CCIGCxXpiUjFoeP8EhwkEjvQcOQAW3A2WaBvm7kWMHgB83PNObPieKz8U0Wy9yZQt9mIyQV6U/NgzWzPUZpK+8wdFIApwyUnf0ik7CKy/fZfD+ow5Y=,iv:uf70/VGU0Q8dEFyFLdgPqJkSL83vzxYjBzpWKqZ2Sv0=,tag:h3YcpE3s7Krl/9o/JxD4PQ==,type:str]
    WEB_API_KEY: ENC[AES256_GCM,data:I4S5Xx4rhbTUMlOsOY3GtRs/XM4TUxJf5nO4K40OLanT2gueN7hq,iv:GijJhsYFBXqVxKX+eZnx37gfW8djUoRGJM3HKSqa1sM=,tag:4QhC8CEckQr0vH5nQW317A==,type:str]
    WEB_API_REFERER: ENC[AES256_GCM,data:0sxk7Yhmis09SGvVF2QNBc9jZBHkRIk=,iv:t33+QCJVXlCcgsLjHETfL7eDpfC2xgc0TN/2or8b72k=,tag:mfDIXSb6Yo31qJfUcTeQvg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:4GnoW7ldv/7NZAKp7RF7Ev1GS8SiVN1vUd8lqV2TzBB8OWHFQIA8LoF694nJPr5yjHuUwH56x2ujGJv1Qvin3jCXjZcqMC6GfXAN,iv:AezxzpY74Y4i5T2NMMt/NAtskJkE30QbyeVXPCX5WHU=,tag:LY+wDpUI9oO8sASz1n6/ow==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:qMBGZkpzULv7WNEYAjjzd3h+lYr3mhgHJV1Mt35WeTBdkeo8DrR16YAS/L8agkArH5N7f8Tgb/68/p56Qq0amkNh8xkXuXTr2ZgPqzrNu0V7jaws33BSpwKBgFS3seeJZRiSlRRBWVF3myp9itxhsJ95KuhzVQoe8IyN52K9Qq0=,iv:lo5tTnH35N3RYBpIJiDaP4VE2+anR5Gb3Hk2fxVf/Rk=,tag:9sFwFnQJhebHSDDx5GalZA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:xYkYB1C41APhmxKeo9Q8URSFjaVAfIXK5wjcgIIsvJiVh4B4gzou1Q9kkWqrKFi1gRqFe+uFlEcC38n3Mo8k2uAPSdCIKFMCZEURLO9S2xAKy+dUMLIMN9a0hRU=,iv:JOSKBL5jRZq/ucp90XMjulxq24TMtnvPS2+pccj9uj4=,tag:5FAraYzgFbeqS/HdToTb+A==,type:str]
    GOOGLE_SHEETS_API_KEY: ENC[AES256_GCM,data:Z/OvnV/r38m0pdb9Gx+tT+vJnE7caqVNPnDQyZlylH4kovViJ9wC,iv:DC4lEUDqu6z2yEWPQvKc6eAOosGXBv7SXBMJh6dE5vI=,tag:pNuLTq7pScvYQsZdHq8nqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dt9j0s8gjecwfnmwyzd6wq8jee3zn84kmlyj0a904anpfuhave4s59n5lq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRkFlVFgyVUxJNzJvemJx
            QzJZZ2JMYzlFZjZwWUFVRGdBMWVwVGUrRVUwCmhlbGQ5TElJRHBpSUY1M0FvUlZz
            aWE2ZStSdkJ4Q2pFNHJNSkQ2eGcyWUkKLS0tIGJGVGdsVFpaZnhQYlhIdDNvMHFJ
            TGZ5S2xSWUQxQ1RkcW9PSHFZRzFGS2sKlobEg40m7k7hH7Q9MqS6Udk5HoTXf9Oi
            8TbnPTuYRb/QRVeTEnFwLx3pIZU8yTQvi4gC/lXVktM0nAwR6lQrvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T04:24:45Z"
    mac: ENC[AES256_GCM,data:JoBZqdBMrHI75rXFPY1clBUrbjbruXo/5+l43mYLUYwMcgSfF9c2XKP5Ptr5aLcl5PmmvoUdNPFi3Z3fybqBzniJvupcrNT8ONIgzQs4L2TYHf9gN8ye0hIve66vIEXvYCUBmvYixiZV8mO+gJ3vCRF6JfGfDJ5fyN7+OX6wx+4=,iv:whwQG6XNboNZCyBk0WlxJXNl6elJPVSzXNejAYD7GnY=,tag:hUPpaX/omBfiPJUap2t+3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
