apiVersion: v1
kind: ConfigMap
metadata:
  name: init
  namespace: postgres
data:
  init.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER etl WITH PASSWORD '$ETL_PASSWORD';
      CREATE DATABASE etl;
      GRANT ALL PRIVILEGES ON DATABASE etl TO etl;
    EOSQL
