apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        envFrom:
        - secretRef:
            name: credentials
        resources:
          requests:
            memory: 1G
          limits:
            memory: 2G
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        - mountPath: /docker-entrypoint-initdb.d
          name: init
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: init
        configMap:
          name: init
