
name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v2.0
    - name: Setup Kustomize
      run: |-
        curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz
        tar xzvf kustomize.tar.gz
        curl -sfLo ksops.tar.gz https://github.com/viaduct-ai/kustomize-sops/releases/download/v3.0.2/ksops_3.0.2_Linux_x86_64.tar.gz
        mkdir -p ~/.config/kustomize/plugin/viaduct.ai/v1/ksops
        tar -C ~/.config/kustomize/plugin/viaduct.ai/v1/ksops xzvf ksops.tar.gz
    - name: Apply
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        XDG_CONFIG_HOME: ~/.config
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}
      run: |-
        mkdir -p ~/.kube
        echo "${KUBECONFIG_CONTENT}" >~/.kube/config
        kustomize build --enable-alpha-plugins . | kubectl apply -f -
